echo ..............................Change directory...
cd /var/www/app/react/portal

echo ..............................Install dependencies Package...
npm install --legacy-peer-deps --verbose

echo ..............................Build project...
npm run build