#echo ..............................uninstallin nodejs...
#echo ..............................remove nodejs...
#sudo apt-get remove nodejs -y
#echo ..............................purge nodejs...
#sudo apt-get purge nodejs -y
#echo ..............................autoremove nodejs...
#sudo apt-get autoremove -y

# echo ..............................update dependencies...
# sudo apt update -y

# echo ..............................installin curl...
# sudo apt-get install -y curl

# echo ..............................installin nvm...
# curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 

echo ..............................installin Node whit NVM...
export NVM_DIR=$HOME/.nvm;
source $NVM_DIR/nvm.sh;
source ~/.bashrc
nvm install node -y
nvm install 16.20.2
nvm use 16.20.2

# echo ..............................install Node...
# curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
# sudo apt install -y nodejs

# echo ..............................install Npm...
# sudo apt install -y npm

echo ..............................Version nodejs...
node -v

echo ..............................Version npm...
npm -v

